apiVersion: v1
kind: Pod
metadata:
  name: readiness-liveness-pod
spec:
  containers:
  - name: my-con
    image: linixacademycontent/candy-service:2
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8081
    readinessProbe:
      httpGet:
        path: /
        port: 80
