apiVersion: v1
kind: Pod
metadata:
  name: my-readiness-probe-pod
spec:
  containers:
  - name: my-readiness-con
    image: nginx
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
