apiVersion: v1
kind: Pod
metadata: 
  name: my-ns-pod
  namespace: my-ns
  labels: 
    app: my-app
spec:
  containers: 
    - name: myapp-container
      image: busybox
      command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]

