apiVersion: v1
kind: Pod
metadata:
  name: multi-con-pod
spec:
  containers:
    - name: nginx-con
      image: nginx:1.15.8
      ports:
        - containerPort: 80
    - name: busy-con
      image: busybox
      command: ['sh', '-c', 'while true; do sleep 30; done;']

