apiVersion: v1
kind: Pod
metadata: 
  name: configmap-volume-pod
spec:
  containers:
  - name: my-con
    image: busybox
    command: ['sh', '-c', "echo $(cat /etc/config/myKey) && sleep 3600"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: my-configmap
