apiVersion: v1
kind: Pod
metadata:
  name: secret-using-pod
spec:
  containers:
  - name: my-con
    image: busybox
    command: ['sh', '-c', "echo $(MY_PASS) && sleep 3600"]
    env:
    - name: MY_PASS
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: myKey 
